name: bastion pipeline

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  terraform_job:
    runs-on: bastionrunner
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          # creds: ${{ secrets.AZURE_CREDENTIALS }}
          # # ClientId of the Azure Service principal created.
          client-id: "c3d8d706-c998-4bca-9647-39fa685bc403"
          # # TenantId of the Azure Service principal created.
          tenant-id: "25da0254-8640-4e13-9016-d3428661a477"
          # # Azure subscriptionId
          subscription-id: "972b29e5-b4b2-4f43-b814-02879737840d"
          # # Set this value to true to enable Azure PowerShell Login in addition to Azure CLI login
          # enable-AzPSSession: # optional
          # # Name of the environment. Supported values are azurecloud, azurestack, azureusgovernment, azurechinacloud, azuregermancloud. Default being azurecloud
          # environment: # optional, default is azurecloud
          # # Set this value to true to enable support for accessing tenants without subscriptions
          # allow-no-subscriptions: # optional
          # # Provide audience field for access-token. Default value is api://AzureADTokenExchange
          # audience: # optional, default is api://AzureADTokenExchange
          # # The type of authentication. Supported values are SERVICE_PRINCIPAL, IDENTITY. Default value is SERVICE_PRINCIPAL
          # auth-type: SERVICE_PRINCIPAL
          
                
      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: Environement
      
      # - name: Terraform Plan
      #   working-directory: Environement
      #   run: terraform plan
      
      # - name: Terraform Apply
      #   working-directory: Environement
      #   run: terraform apply -auto-approve
